#define MIC_PIN A0
#define POT_SENSITIVITY_PIN A1
#define POT_DURATION_PIN A2
#define LED_PIN 5
#define BUZZER_PIN 6

#define SAMPLE_WINDOW 50

#define ATTACK 3
#define RELEASE 1

#define FAST_FADE_DURATION 100
#define MEDIUM_FADE_DURATION 500
#define SLOW_FADE_DURATION 1000

#define BUZZER_FREQUENCY 440